# Generated by Django 4.1.7 on 2023-05-24 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_data_criaçao_people_data_criacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('tamanho', models.FloatField()),
                ('tipo', models.CharField(max_length=20)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.people')),
            ],
        ),
    ]
