# Generated by Django 4.1.7 on 2023-05-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='peso',
        ),
        migrations.AddField(
            model_name='people',
            name='sexo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='raca',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
